image: node:8.12.0

cache:
  paths:
    - node_modules/

variables:
  COMPOSER_CMD: "./node_modules/.bin/composer"
  COMPOSER_DEV_CARD_LOCATION: "http://ec2-54-245-150-59.us-west-2.compute.amazonaws.com:8080/fabric-tools/fabric-scripts/hlfv1/composer/creds/"

stages:
  - security-and-setup
  - test
  - release-and-deploy

install-dependencies:
  stage: security-and-setup
  script: npm install --progress=false

npm-audit-security-check:
  stage: security-and-setup
  allow_failure: true
  script: npm audit

retire-security-check:
  stage: test
  allow_failure: true
  script: ./node_modules/.bin/retire -p
  dependencies:
    - install-dependencies

lint:
  stage: test
  script: npm run lint
  dependencies:
    - install-dependencies

unit-tests:
  stage: test
  script: npm run test:unit
  dependencies:
    - install-dependencies

bdd-tests:
  stage: test
  script: npm run test:bdd
  dependencies:
    - install-dependencies

patch-deploy-publish:
  stage: release-and-deploy
  before_script:
    - echo ${COMPOSER_DEV_CARD_LOCATION}
    - wget ${COMPOSER_DEV_CARD_LOCATION}
    - ${COMPOSER_CMD} card import --file peer-admin.card
    - ${COMPOSER_CMD} card list
    # generate ssh key
    - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
    - mkdir -p ~/.ssh    
    - chmod 700 ~/.ssh
    ## Use ssh-keyscan to scan the keys of the private server
    - ssh-keyscan ${DEPLOY_SERVER} >> ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts
    ## Alternatively, put the response in a variable
    ## - echo "$SSH_SERVER_HOSTKEYS" > ~/.ssh/known_hosts
    ## - chmod 644 ~/.ssh/known_hosts

  script:
    - git config user.name "Gitlab CI" && git config user.email "some-product-team@codecentric.de"
    - NEW_APP_VERSION="v0.0.2"    
    - echo "Deploy project on server ${DEPLOY_SERVER}"
    ## remove existing file peer-admin.card
    - ssh ubuntu@${DEPLOY_SERVER}
        "echo ${COMPOSER_DEV_CARD_LOCATION} 
        && wget ${COMPOSER_DEV_CARD_LOCATION}
         && composer card import --file peer-admin.card
         && composer card list
         && mkdirp ./dist
         && composer archive create  --sourceType dir --sourceName . -a ./dist/engine-supplychain.bna
         && composer network install -a dist/engine-supplychain.bna --card PeerAdmin@hlfv1
         && composer network install -a dist/engine-supplychain.bna --card PeerAdmin@hlfv1
         && composer network start -n engine-supplychain -V ${NEW_APP_VERSION/v/} --networkAdmin admin --networkAdminEnrollSecret adminpw --card PeerAdmin@hlfv11 --file local-network-admin.card || $composer network upgrade -c PeerAdmin@hlfv1 -n engine-supplychain -V ${NEW_APP_VERSION/v/}"
  after_script:
    - git push https://mygitlabname:${PRIVATE_ACCESS_TOKEN_MYGITLABNAME}@gitlab.com/${CI_PROJECT_PATH}.git HEAD:master --follow-tags
  only:
    - master
    - gitlab-ci-pipeline
  artifacts:
    paths:
      - dist/engine-supplychain.bna
      - local-network-admin.card
    expire_in: 2 week
